### ISSUE TITLE
사용자는 클랩 글을 읽고 박수를 눌러 만족도를 표현할 수 있다

### ISSUE THREAD

**Issue by shinsunyoung** [Lubycon/clelab-backend#144]
# Description

> 박수 기능 추가

## To-do

* [x] DB 스키마 변경
* [x] api 정의서 추가
* [x] 박수 카운트 증가 api 추가
* [x] 박수 카운트 컬럼 조회 api에 추가
