### ISSUE TITLE
API 리뷰 내용을 바탕으로 API 수정

### ISSUE THREAD

**Issue by shinsunyoung** [Lubycon/clelab-backend#19]
## Description

> [민석님과 결정했던 사항 슬랙](https://lubycon-hub.slack.com/archives/C01U74A4BHV/p1619772301026900)
[추가 API 리뷰를 통해 결정된 사항 슬랙](https://lubycon-hub.slack.com/archives/C01U74A4BHV/p1619772417027800)

## To-do

* [x] 통일성을 위해 null값이 아닌 빈 객체를 반환한다. 
* [x] 섹션 내용을 가져오는 값을 `order`에서 `section_id`으로 변경한다.
* [x] GlobalExceptionHandler에서 `@Slf4j` 삭제
