### ISSUE TITLE
로그 형식 JSON으로 변경

### ISSUE THREAD

**Issue by shinsunyoung** [Lubycon/clelab-backend#81]
## Description

> 로그 포맷을 JSON으로 변경한다. 

01:03:08.505 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'

이런 못생긴 로그는 이제 안녕 ~ 👋😉🤚

## To-do

* [x] 형식 변경

**Comment by shinsunyoung** [comment]
조대협님의 블로그
- [ ] [로그 시스템 #1 - 자바 로그 프레임웍](https://bcho.tistory.com/1312?category=431297)
- [ ] [로그 시스템 #2- 자바 로그 & JSON 로그 포맷](https://bcho.tistory.com/1313?category=431297)
- [ ] [로그 프레임워크 #3 - JSON 로그에 필드 추가하기](https://bcho.tistory.com/1314?category=431297)

다 읽을 때 마다 체쿠하기
