### ISSUE TITLE
구독 신청 API 추가

### ISSUE THREAD

**Issue by shinsunyoung** [Lubycon/clelab-backend#86]
## Description

> 사용자는 이메일로 새로 나온 코스의 소식을 받기 위해 클랩.io 내부에서 구독 신청을 할 수 있다

## To-do
* [x] Swagger에 추가
* [x] 구독 신청 API 추가
* [x] 중복된 이메일은 예외처리해두기
* [x] 이메일 인덱스 추가하기
